#!/bin/sh /etc/rc.common

START=98
PID=/var/run/freewifi-uhttpd.pid
CONFIG=/etc/freewifi/config

FREE_IP=10.18.30.1
FREE_PORT=2081
[ -r "$CONFIG" ] && . "$CONFIG"

start() {
	/usr/sbin/freewifi init
	start-stop-daemon -K -q -p "$PID" 2>/dev/null || true
	start-stop-daemon -S -q -b -m -p "$PID" -x /usr/sbin/uhttpd -- \
		-f -p "$FREE_IP:$FREE_PORT" -h /www/freewifi -x /cgi-bin \
		-E /cgi-bin/freewifi -t 30 -T 30 -n 2 -N 10
}

stop() {
	start-stop-daemon -K -q -p "$PID" 2>/dev/null || true
	rm -f "$PID"
}

reload() {
	stop
	start
}
